<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>A large, organized color expansion for Town of Us: Mira.</Description>
    <Product>ChromaMates</Product>
    <AssemblyTitle>ChromaMates</AssemblyTitle>
    <AssemblyName>ChromaMates</AssemblyName>
    <RootNamespace>ChromaMates</RootNamespace>
    <PackageId>ChromaMates</PackageId>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <Version>1.3.10</Version>
  </PropertyGroup>

  <ItemGroup>
    <None Include="LICENSE.txt" Pack="true" PackagePath="\" />
    <None Update="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <Import Project="AmongUs.props" />
</Project>
