namespace ChromaMates.Colors;

internal readonly record struct SemanticColorAnchor(
    ColorSelectorCategory Category,
    string Name,
    uint Rgb);

internal readonly record struct SemanticColorTone(
    string Prefix,
    float SaturationScale,
    float ValueScale,
    float ValueOffset);

internal static class SemanticColorNames
{
    internal static readonly SemanticColorTone[] Tones =
    [
        new("", 1.00f, 1.00f, 0.00f),
        new("White", 0.25f, 0.35f, 0.65f),
        new("Frosted", 0.35f, 0.45f, 0.53f),
        new("Pale", 0.45f, 0.55f, 0.42f),
        new("Pastel", 0.55f, 0.62f, 0.34f),
        new("Light", 0.68f, 0.72f, 0.26f),
        new("Soft", 0.62f, 0.78f, 0.18f),
        new("Faded", 0.48f, 0.78f, 0.12f),
        new("Dusty", 0.58f, 0.72f, 0.08f),
        new("Muted", 0.42f, 0.70f, 0.06f),
        new("Clear", 0.88f, 0.92f, 0.06f),
        new("Bright", 1.10f, 0.95f, 0.08f),
        new("Vivid", 1.22f, 0.90f, 0.07f),
        new("Fresh", 1.00f, 0.88f, 0.05f),
        new("Rich", 1.12f, 0.78f, 0.00f),
        new("Deep", 1.02f, 0.62f, 0.00f),
        new("Dusky", 0.72f, 0.53f, 0.00f),
        new("Smoky", 0.45f, 0.45f, 0.00f),
        new("Dark", 0.88f, 0.36f, 0.00f),
        new("Shadow", 0.68f, 0.27f, 0.00f),
        new("Black", 0.55f, 0.18f, 0.00f)
    ];

    internal static readonly SemanticColorAnchor[] Anchors =
    [
        new(ColorSelectorCategory.Reds, "Apple", 0xD3212Du),
        new(ColorSelectorCategory.Reds, "Cherry", 0xC21833u),
        new(ColorSelectorCategory.Reds, "Rose", 0xC21E56u),
        new(ColorSelectorCategory.Reds, "Ruby", 0x9B111Eu),
        new(ColorSelectorCategory.Reds, "Garnet", 0x733635u),
        new(ColorSelectorCategory.Reds, "Cranberry", 0x9E003Au),
        new(ColorSelectorCategory.Reds, "Tomato", 0xFF6347u),
        new(ColorSelectorCategory.Reds, "Poppy", 0xDC343Bu),
        new(ColorSelectorCategory.Reds, "Brick", 0xB22222u),
        new(ColorSelectorCategory.Reds, "Currant", 0x8B0000u),
        new(ColorSelectorCategory.Reds, "Mahogany", 0xC04000u),
        new(ColorSelectorCategory.Reds, "Paprika", 0x8D0226u),
        new(ColorSelectorCategory.Reds, "Beet", 0x8A1538u),
        new(ColorSelectorCategory.Reds, "Pepper", 0xA91101u),
        new(ColorSelectorCategory.Reds, "Lobster", 0xCC4E5Cu),
        new(ColorSelectorCategory.Reds, "Cardinal", 0xC41E3Au),
        new(ColorSelectorCategory.Reds, "Pomegranate", 0xC0392Bu),
        new(ColorSelectorCategory.Reds, "Sequoia", 0x8B2E24u),

        new(ColorSelectorCategory.Oranges, "Apricot", 0xFBCEB1u),
        new(ColorSelectorCategory.Oranges, "Peach", 0xFFCBA4u),
        new(ColorSelectorCategory.Oranges, "Tangerine", 0xF28500u),
        new(ColorSelectorCategory.Oranges, "Pumpkin", 0xFF7518u),
        new(ColorSelectorCategory.Oranges, "Carrot", 0xED9121u),
        new(ColorSelectorCategory.Oranges, "Amber", 0xFFBF00u),
        new(ColorSelectorCategory.Oranges, "Copper", 0xB87333u),
        new(ColorSelectorCategory.Oranges, "Persimmon", 0xEC5800u),
        new(ColorSelectorCategory.Oranges, "Cantaloupe", 0xFFA62Fu),
        new(ColorSelectorCategory.Oranges, "Marmalade", 0xD16002u),
        new(ColorSelectorCategory.Oranges, "Marigold", 0xEAA221u),
        new(ColorSelectorCategory.Oranges, "Terracotta", 0xE2725Bu),
        new(ColorSelectorCategory.Oranges, "Butterscotch", 0xD48827u),
        new(ColorSelectorCategory.Oranges, "Papaya", 0xFF7F50u),
        new(ColorSelectorCategory.Oranges, "Nectarine", 0xFF8656u),
        new(ColorSelectorCategory.Oranges, "Saffron", 0xF4C430u),
        new(ColorSelectorCategory.Oranges, "Cider", 0xB56727u),
        new(ColorSelectorCategory.Oranges, "Clay", 0xB66A50u),

        new(ColorSelectorCategory.Yellows, "Lemon", 0xFFF700u),
        new(ColorSelectorCategory.Yellows, "Banana", 0xFFE135u),
        new(ColorSelectorCategory.Yellows, "Butter", 0xFFFD74u),
        new(ColorSelectorCategory.Yellows, "Honey", 0xFFC30Bu),
        new(ColorSelectorCategory.Yellows, "Mustard", 0xD2B04Cu),
        new(ColorSelectorCategory.Yellows, "Corn", 0xFBEC5Eu),
        new(ColorSelectorCategory.Yellows, "Daffodil", 0xFFFF31u),
        new(ColorSelectorCategory.Yellows, "Sunflower", 0xFFDA03u),
        new(ColorSelectorCategory.Yellows, "Canary", 0xFFFF99u),
        new(ColorSelectorCategory.Yellows, "Wheat", 0xF5DEB3u),
        new(ColorSelectorCategory.Yellows, "Straw", 0xE4D96Fu),
        new(ColorSelectorCategory.Yellows, "Pineapple", 0xE6AE25u),
        new(ColorSelectorCategory.Yellows, "Custard", 0xF7E7A9u),
        new(ColorSelectorCategory.Yellows, "Dandelion", 0xF0E130u),
        new(ColorSelectorCategory.Yellows, "Flax", 0xEEDC82u),
        new(ColorSelectorCategory.Yellows, "Maize", 0xF4D054u),
        new(ColorSelectorCategory.Yellows, "Sponge", 0xFBCB4Au),
        new(ColorSelectorCategory.Yellows, "Yolk", 0xE2B051u),

        new(ColorSelectorCategory.Greens, "Lime", 0x32CD32u),
        new(ColorSelectorCategory.Greens, "Mint", 0x98FF98u),
        new(ColorSelectorCategory.Greens, "Moss", 0x8A9A5Bu),
        new(ColorSelectorCategory.Greens, "Fern", 0x4F7942u),
        new(ColorSelectorCategory.Greens, "Olive", 0x808000u),
        new(ColorSelectorCategory.Greens, "Sage", 0x9CAF88u),
        new(ColorSelectorCategory.Greens, "Basil", 0x32612Du),
        new(ColorSelectorCategory.Greens, "Avocado", 0x568203u),
        new(ColorSelectorCategory.Greens, "Pine", 0x01796Fu),
        new(ColorSelectorCategory.Greens, "Shamrock", 0x009E60u),
        new(ColorSelectorCategory.Greens, "Malachite", 0x0BDA51u),
        new(ColorSelectorCategory.Greens, "Jade", 0x00A86Bu),
        new(ColorSelectorCategory.Greens, "Seaweed", 0x354A21u),
        new(ColorSelectorCategory.Greens, "Cactus", 0x587058u),
        new(ColorSelectorCategory.Greens, "Matcha", 0x7B9278u),
        new(ColorSelectorCategory.Greens, "Clover", 0x3EA055u),
        new(ColorSelectorCategory.Greens, "Bamboo", 0x6B8E23u),
        new(ColorSelectorCategory.Greens, "Pistachio", 0x93C572u),

        new(ColorSelectorCategory.Cyans, "Lagoon", 0x4CB7A5u),
        new(ColorSelectorCategory.Cyans, "Glacier", 0x78BFD6u),
        new(ColorSelectorCategory.Cyans, "Ice", 0x99FFFFu),
        new(ColorSelectorCategory.Cyans, "Aquamarine", 0x7FFFD4u),
        new(ColorSelectorCategory.Cyans, "Turquoise", 0x40E0D0u),
        new(ColorSelectorCategory.Cyans, "Teal", 0x008080u),
        new(ColorSelectorCategory.Cyans, "Pool", 0x00B7EBu),
        new(ColorSelectorCategory.Cyans, "Seaglass", 0x7AC5B4u),
        new(ColorSelectorCategory.Cyans, "Opal", 0xA8C3BCu),
        new(ColorSelectorCategory.Cyans, "Fjord", 0x4B6D7Au),
        new(ColorSelectorCategory.Cyans, "Spruce", 0x0A5F5Fu),
        new(ColorSelectorCategory.Cyans, "Patina", 0x639A8Fu),
        new(ColorSelectorCategory.Cyans, "Apatite", 0x43B3AEu),
        new(ColorSelectorCategory.Cyans, "Beryl", 0x4AC7B7u),
        new(ColorSelectorCategory.Cyans, "Surf", 0x00A9A5u),
        new(ColorSelectorCategory.Cyans, "Mintleaf", 0x3EB489u),
        new(ColorSelectorCategory.Cyans, "Celadon", 0xACE1AFu),
        new(ColorSelectorCategory.Cyans, "Harbor", 0x3AB0A2u),

        new(ColorSelectorCategory.Blues, "Sky", 0x87CEEBu),
        new(ColorSelectorCategory.Blues, "Ocean", 0x0077BEu),
        new(ColorSelectorCategory.Blues, "Sapphire", 0x0F52BAu),
        new(ColorSelectorCategory.Blues, "Cobalt", 0x0047ABu),
        new(ColorSelectorCategory.Blues, "Denim", 0x1560BDu),
        new(ColorSelectorCategory.Blues, "Blueberry", 0x4F86F7u),
        new(ColorSelectorCategory.Blues, "Navy", 0x000080u),
        new(ColorSelectorCategory.Blues, "Ink", 0x1B1B4Bu),
        new(ColorSelectorCategory.Blues, "Lapis", 0x26619Cu),
        new(ColorSelectorCategory.Blues, "Cornflower", 0x6495EDu),
        new(ColorSelectorCategory.Blues, "Steel", 0x4682B4u),
        new(ColorSelectorCategory.Blues, "Periwinkle", 0xCCCCFFu),
        new(ColorSelectorCategory.Blues, "Cerulean", 0x007BA7u),
        new(ColorSelectorCategory.Blues, "Bluejay", 0x2B59C3u),
        new(ColorSelectorCategory.Blues, "Rain", 0x5D8AA8u),
        new(ColorSelectorCategory.Blues, "Slate", 0x6A5ACDu),
        new(ColorSelectorCategory.Blues, "Iris", 0x5D3FD3u),
        new(ColorSelectorCategory.Blues, "Twilight", 0x273B7Au),

        new(ColorSelectorCategory.Purples, "Grape", 0x6F2DA8u),
        new(ColorSelectorCategory.Purples, "Plum", 0x8E4585u),
        new(ColorSelectorCategory.Purples, "Violet", 0x8F00FFu),
        new(ColorSelectorCategory.Purples, "Lavender", 0xB57EDCu),
        new(ColorSelectorCategory.Purples, "Amethyst", 0x9966CCu),
        new(ColorSelectorCategory.Purples, "Lilac", 0xC8A2C8u),
        new(ColorSelectorCategory.Purples, "Orchid", 0xDA70D6u),
        new(ColorSelectorCategory.Purples, "Eggplant", 0x614051u),
        new(ColorSelectorCategory.Purples, "Mulberry", 0xC54B8Cu),
        new(ColorSelectorCategory.Purples, "Fig", 0x7C4568u),
        new(ColorSelectorCategory.Purples, "Wineberry", 0x673147u),
        new(ColorSelectorCategory.Purples, "Thistle", 0xD8BFD8u),
        new(ColorSelectorCategory.Purples, "Heather", 0x9E7BB5u),
        new(ColorSelectorCategory.Purples, "Wisteria", 0xC9A0DCu),
        new(ColorSelectorCategory.Purples, "Raisin", 0x4B3048u),
        new(ColorSelectorCategory.Purples, "Damson", 0x4D285Du),
        new(ColorSelectorCategory.Purples, "Mauve", 0xE0B0FFu),
        new(ColorSelectorCategory.Purples, "Aubergine", 0x693B58u),

        new(ColorSelectorCategory.Pinks, "Flamingo", 0xFC8EACu),
        new(ColorSelectorCategory.Pinks, "Bubblegum", 0xFFC1CCu),
        new(ColorSelectorCategory.Pinks, "CottonCandy", 0xFFBCD9u),
        new(ColorSelectorCategory.Pinks, "Carnation", 0xFFA6C9u),
        new(ColorSelectorCategory.Pinks, "Peony", 0xE7417Au),
        new(ColorSelectorCategory.Pinks, "Watermelon", 0xFC6C85u),
        new(ColorSelectorCategory.Pinks, "Guava", 0xFF7F7Fu),
        new(ColorSelectorCategory.Pinks, "Dragonfruit", 0xF35A8Du),
        new(ColorSelectorCategory.Pinks, "Shell", 0xFFB7C5u),
        new(ColorSelectorCategory.Pinks, "Blossom", 0xDE5D83u),
        new(ColorSelectorCategory.Pinks, "Taffy", 0xF987C5u),
        new(ColorSelectorCategory.Pinks, "Ballet", 0xF79AC0u),
        new(ColorSelectorCategory.Pinks, "Azalea", 0xF7C8DAu),
        new(ColorSelectorCategory.Pinks, "Begonia", 0xFA6E79u),
        new(ColorSelectorCategory.Pinks, "Cosmos", 0xFF8D8Du),
        new(ColorSelectorCategory.Pinks, "Salmon", 0xFA8072u),
        new(ColorSelectorCategory.Pinks, "Sorbet", 0xF78FA7u),
        new(ColorSelectorCategory.Pinks, "Petal", 0xF4C2C2u),

        new(ColorSelectorCategory.Neutrals, "Snow", 0xFFFAFAu),
        new(ColorSelectorCategory.Neutrals, "Chalk", 0xF5F5F0u),
        new(ColorSelectorCategory.Neutrals, "Pearl", 0xEAE0C8u),
        new(ColorSelectorCategory.Neutrals, "Ivory", 0xFFFFF0u),
        new(ColorSelectorCategory.Neutrals, "Linen", 0xFAF0E6u),
        new(ColorSelectorCategory.Neutrals, "Ash", 0xB2BEB5u),
        new(ColorSelectorCategory.Neutrals, "Smoke", 0x848884u),
        new(ColorSelectorCategory.Neutrals, "Granite", 0x676767u),
        new(ColorSelectorCategory.Neutrals, "Charcoal", 0x36454Fu),
        new(ColorSelectorCategory.Neutrals, "Coal", 0x2B2B2Bu),
        new(ColorSelectorCategory.Neutrals, "Onyx", 0x353839u),
        new(ColorSelectorCategory.Neutrals, "Graphite", 0x41424Cu),
        new(ColorSelectorCategory.Neutrals, "Silver", 0xC0C0C0u),
        new(ColorSelectorCategory.Neutrals, "Concrete", 0x9A9A9Au),
        new(ColorSelectorCategory.Neutrals, "Mushroom", 0xBDACA3u),
        new(ColorSelectorCategory.Neutrals, "Parchment", 0xE9DCC9u),
        new(ColorSelectorCategory.Neutrals, "Flint", 0x575D5Eu),
        new(ColorSelectorCategory.Neutrals, "Obsidian", 0x1C1C1Cu)
    ];
}
